// xpute-core/status/errno.spec.rs
//
// GENERATED by script/spec.ts from errno.json — do not edit.
//
// POSIX/Linux-aligned negative errno

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum Errno {
    OK = 0, // Success

    // ---- Generic ----
    EPERM = -1,    // Operation not permitted
    ENOENT = -2,   // No such file or directory / entry not found
    ESRCH = -3,    // No such process
    EINTR = -4,    // Interrupted system call
    EIO = -5,      // I/O error
    ENXIO = -6,    // No such device or address
    E2BIG = -7,    // Argument list too long / object too large for fixed local cap
    ENOEXEC = -8,  // Exec format error
    EBADF = -9,    // Bad file descriptor / bad handle
    ECHILD = -10,  // No child processes
    EAGAIN = -11,  // Try again / Resource temporarily unavailable
    ENOMEM = -12,  // Out of memory
    EACCES = -13,  // Permission denied
    EFAULT = -14,  // Bad address
    EBUSY = -16,   // Device or resource busy
    EEXIST = -17,  // File exists / duplicate bind
    EXDEV = -18,   // Cross-device link
    ENODEV = -19,  // No such device
    ENOTDIR = -20, // Not a directory
    EISDIR = -21,  // Is a directory
    EINVAL = -22,  // Invalid argument
    ENFILE = -23,  // File table overflow (system-wide)
    EMFILE = -24,  // Too many open files (process)
    ENOTTY = -25,  // Not a tty
    EFBIG = -27,   // File too large / payload too large
    ENOSPC = -28,  // No space left on device / local mailbox full
    ESPIPE = -29,  // Illegal seek
    EROFS = -30,   // Read-only file system
    EMLINK = -31,  // Too many links
    EPIPE = -32,   // Broken pipe
    EDOM = -33,    // Math argument out of domain
    ERANGE = -34,  // Math result not representable
    ENOSYS = -38,  // Function not implemented

    // ---- Protocol / Message / Encoding ----
    EPROTO = -71,    // Protocol error
    EBADMSG = -74,   // Bad message (protocol/frame/payload invalid)
    EOVERFLOW = -75, // Value too large for target type / overflow
    EMSGSIZE = -90,  // Message too long / packet too large
    ENOTSUP = -95,   // Operation not supported
    EILSEQ = -84,    // Illegal byte sequence (decode/encoding failure)

    // ---- Endpoint / Addressing ----
    EADDRINUSE = -98,    // Address already in use
    EADDRNOTAVAIL = -99, // Cannot assign requested address

    // ---- Network / Transport (Linux asm-generic/errno.h aligned) ----
    ENETDOWN = -100,     // Network is down
    ENETUNREACH = -101,  // Network is unreachable
    ENETRESET = -102,    // Network dropped connection because of reset
    ECONNABORTED = -103, // Software caused connection abort
    ECONNRESET = -104,   // Connection reset by peer
    ENOBUFS = -105,      // No buffer space available
    EISCONN = -106,      // Transport endpoint is already connected
    ENOTCONN = -107,     // Transport endpoint is not connected
    ESHUTDOWN = -108,    // Cannot send after transport endpoint shutdown
    ETOOMANYREFS = -109, // Too many references
    ETIMEDOUT = -110,    // Connection timed out
    ECONNREFUSED = -111, // Connection refused
    EHOSTDOWN = -112,    // Host is down
    EHOSTUNREACH = -113, // No route to host
    EALREADY = -114,     // Operation already in progress
    EINPROGRESS = -115,  // Operation now in progress

    // ---- Lifecycle / Cancellation ----
    ECANCELED = -125, // Operation canceled
}

// Result pair: (errno, data)
//
// Conventions:
// - errno == Errno::OK  -> success
// - errno != Errno::OK  -> failure
// - data == None        -> no payload
//
// `None` is the "no value / no payload" sentinel: the empty result slot,
// nothing about pointers.
pub type ErrnoResult<T> = (Errno, Option<T>);
